name: CI

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.3.x"

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Run spell check
        run: npm run spell-check

      - name: Run prettier
        run: npm run prettier-check

      - name: Run lint
        run: npm run lint

      - name: Run test & coverage
        run: npm run test:coverage
